.TH PRIMAL++ 1 primal++\-VERSION
.SH NAME
primal++ \- Computes prime numbers using trial division
.SH SYNOPSIS
.B primal++
.RB [ \-? ]
.RB [ \-c
.IR ceiling ]
.RB [ \-i
.IR index ]
.RB [ \-t
.IR candidate ]
.SH OPTIONS
.TP
.B \-?
Show usage information
.TP
.B \-c
Compute every prime below a given ceiling value
.TP
.B \-i
Compute the prime at a given index in the series
.TP
.B \-t
Perform a primality test on a given candidate integer
