.TH PRIMAL++ 1 primal++\-VERSION
.SH NAME
primal++ \- Computes prime numbers using a Sieve of Eratosthenes.
.SH SYNOPSIS
.B primal++
.RB [ \-? ]
.RB [ \-l
.IR CEILING ]
.RB [ \-n
.IR INDEX ]
.RB [ \-t
.IR NUMBER ]
.SH OPTIONS
.TP
.B \-?
Show usage information.
.TP
.B \-l CEILING
List primes up to a value.
.TP
.B \-n INDEX
Find the Nth prime number.
.TP
.B \-t NUMBER
Test if a number is prime.
