.TH PRIMAL++ 1 primal++\-VERSION
.SH NAME
primal++ \- Computes prime numbers using a Sieve of Eratosthenes.
.SH SYNOPSIS
.B primal++
.RB [ \-? ]
.RB [ \-c
.IR CEILING ]
.RB [ \-i
.IR INDEX ]
.RB [ \-t
.IR NUMBER ]
.SH OPTIONS
.TP
.B \-?
Show usage information
.TP
.B \-c
List every prime below a ceiling.
.TP
.B \-i
Find the Nth prime in the series.
.TP
.B \-t
Perform a prrimality test on a number.
