.TH PRIMAL 1 primal\-VERSION
.SH NAME
primal \- Searches for primes using trial division.
.SH SYNOPSIS
.B primal
.RB [ \-? ]
.RB [ \-n
.IR number ]
.RB [ \-i
.IR index ]
.RB [ \-c
.IR ceiling ]
.SH OPTIONS
.TP
.B \-?
Show usage information
.TP
.B \-n
Check whether a number is prime
.TP
.B \-i
Calculate the Nth prime number
.TP
.B \-c
List all primes below the search ceiling
